version: "3.9"

networks:
  blog-app-test-net:
    name: blog-app-test-net
    driver: bridge

volumes:
  db_data: {}

services:
  backend:
    container_name: backend    
    mem_limit: 512m
    mem_reservation: 64M
    cpus: 0.5
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - "./backend:/app"
    ports:
      - "9494:9494"
    environment:
      - BACKEND_ADDRESS=:9494
      - DATABASE_NAME=blogTest
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - GIN_MODE=release
      - GIN_JWT_SECRET=testsecretkey
    networks:
      - blog-app-test-net
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9494/health_check"]
      timeout: 5s
      retries: 10
    depends_on:
      mariadb:
          condition: service_healthy
  
  testbackendapi:
    container_name: testbackendapi
    build:
      context: ./tests/integration/backendapi
      dockerfile: Dockerfile.local
    volumes:
      - "./tests/integration/backendapi:/app"
    environment:
      - BACKEND_BASE_URL=http://backend:9494/
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=blogTest
    networks:
      - blog-app-test-net
    depends_on:
      backend:
          condition: service_healthy

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3308"
    networks:
      - blog-app-test-net
    healthcheck:
      test: ["CMD", "mysqladmin", "-ppassword" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
