{
 "title": "Backend Metrics",
 "description": "Backend Metrics",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "testid", "query": { "query": "label_values(testid)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   { "name": "url", "query": { "query": "label_values(url)" } }
  ]
 },
 "panels": [
  {
   "title": "API Call Response Time Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(method,url) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "P0.5 - {{ method  }} - {{ url }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(method,url) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "P0.95 - {{ method  }} - {{ url }}"
    }
   ]
  },
  {
   "title": "(Backend) HTTP Request per Second - Breakdown per service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method,path) (rate(http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\"}"
    },
    {
     "expr": "histogram_quantile(0, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Time Diff API Call vs DB Query Call",
   "type": "timeseries",
   "description": "Difference in time between the API call overall time and the DB Query Call time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method,url) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "Client API Call P95 ({{ method }} {{ url }})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,method,path) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Server API Call P95 ({{ method }} {{ path }})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,method) (rate(post_repository_summary_bucket[$__rate_interval])))",
     "legendFormat": "Server DB Call P95 {{ method }}"
    },
    {
     "expr": "sum by (method) (rate(post_repository_summary_sum[$__rate_interval])/rate(post_repository_summary_count[$__rate_interval]))",
     "legendFormat": "Server DB Call Avg {{ method }}"
    },
    {
     "expr": "sum by(method,path) (rate(http_request_duration_seconds_sum[$__rate_interval])/rate(http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Server API Call Avg ({{ method }} {{ path }})"
    }
   ]
  }
 ]
}